PREFIX d2s: <http://data2services/data/hgnc/hgnc_complete_set.ts/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX bioentity: <http://bioentity.io/vocab/>
PREFIX dcterms: <http://purl.org/dc/terms/>
CONSTRUCT { 
    ?hgncUri a bioentity:Gene .
    ?hgncUri rdfs:label ?geneName .
    ?hgncUri dcterms:identifier ?hgncid .
    ?hgncUri bioentity:id ?hgncUri .
    ?hgncUri bioentity:systematic_synonym ?symbol .}
WHERE { SELECT ?s ?hgncid ?geneName ?symbol ?hgncUri {
    ?s d2s:ApprovedName ?geneName .
    ?s d2s:HgncId ?hgncid .
    ?s d2s:ApprovedSymbol ?symbol .
    ?s ?p ?o .
    BIND (iri(concat("http://identifiers.org/", lcase (?hgncid) ) ) AS ?hgncUri ) }
}